=== kunnaaalll/College/Web Tech/Pract - 14/A14.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates and open the template in the editor.
-->
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="class">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                        <xs:element name="name" type="xs:string" />
                        <xs:element name="age" type="xs:int" />
                        <xs:element name="marks" type="xs:int" />
                        <!--<xs:element
                        name="color" type="xs:string" default="red"/>
                        <xs:element name="color" type="xs:string" fixed="red"/>
                        <xs:element name="dateborn" type="xs:date"/>
                        <price>-999.5230</price>
                        -->
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kunnaaalll/College/Web Tech/Pract - 14/index.xml
<?xml version="1.0" encoding="UTF-8"?>

<class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="A14.xsd">
    <student>
        <name>Kunal</name>
        <age>27</age>
        <marks>700</marks>
    </student>

    <student>
        <name>Diya</name>
        <age>25</age>
        <marks>650</marks>
    </student>

    <student>
        <name>Meera</name>
        <age>25</age>
        <marks>678</marks>
    </student>

    <student>
        <name>Naman</name>
        <age>22</age>
        <marks>578</marks>
    </student>
</class>
